"""Shared pytest fixtures and Hypothesis strategies for the profile_suite test suite.

This is a placeholder for shared strategies. As the pure-logic core lands (Config,
GridSpec, result models, aggregation, timing/memory reconciliation, run-loop state
machine), the strategies that generate their inputs will be defined here and reused
across the property tests so each test stays a single focused property.

Strategies to be added (per design.md Testing Strategy / tasks.md):
    - config_pairs()       -> ordered (from, to) Config pairs        (Property 2)
    - grids()              -> GridSpec instances                     (Property 1)
    - repeat_outcomes()    -> interleavings of success/failure runs  (Properties 4, 11)
    - monotonic_timestamps() -> t0 <= t1 <= t2 <= t3 on one clock    (Property 3)
    - memory_reports()     -> parsed memory reports + slot counts    (Property 7)
    - budgets()            -> per-Config peaks + budget values       (Property 9)
    - campaign_defs()      -> valid and invalid campaign definitions (Property 14)

Keeping them centralized here avoids duplication and keeps each property test a
single, named test as required by the spec's testing conventions.
"""

from hypothesis import strategies as st

from profile_suite.config import Config, GridSpec
from profile_suite.validation import RECOGNIZED_PLATFORMS

# Small value pools so generated pairs frequently collide on some fields and
# differ on others, exercising every change_type branch (and the identical case).
_QUANT_FILES = ["q4_k_m.gguf", "q8_0.gguf", "f16.gguf"]
_CTX_LENGTHS = [2048, 4096, 32768]
_SLOT_COUNTS = [1, 2, 4]


def configs() -> st.SearchStrategy[Config]:
    """A Hypothesis strategy generating single :class:`Config` instances.

    Field values are drawn from small pools so that pairs of Configs frequently
    share some fields and differ on others, giving good coverage of the
    change_type classification branches.
    """
    return st.builds(
        Config,
        quant_file=st.sampled_from(_QUANT_FILES),
        ctx_length=st.sampled_from(_CTX_LENGTHS),
        slot_count=st.sampled_from(_SLOT_COUNTS),
    )


def config_pairs() -> st.SearchStrategy[tuple[Config, Config]]:
    """A Hypothesis strategy generating ordered ``(from, to)`` Config pairs.

    The pair may be identical or may differ in any combination of fields, so the
    consuming property test sees slot-reshape, model-reload, combined, and the
    identical (ValueError) case.
    """
    return st.tuples(configs(), configs())


def grids() -> st.SearchStrategy[GridSpec]:
    """A Hypothesis strategy generating :class:`GridSpec` instances.

    Each axis (quant files, context lengths, slot counts) is drawn from the same
    small value pools used for single Configs, as a list that may be empty and
    may contain duplicate values. Drawing from small pools makes within-axis
    duplicates and cross-axis collisions frequent, so the consuming property test
    exercises the duplicate-free, deterministic cross-product behavior of
    :func:`expand_grid`.
    """
    return st.builds(
        GridSpec,
        quant_files=st.lists(st.sampled_from(_QUANT_FILES), max_size=5),
        ctx_lengths=st.lists(st.sampled_from(_CTX_LENGTHS), max_size=5),
        slot_counts=st.lists(st.sampled_from(_SLOT_COUNTS), max_size=5),
    )


# Realistic monotonic-clock range: nanoseconds (``time.monotonic_ns()`` is an
# arbitrary-origin counter). The upper bound keeps values in a plausible
# multi-day window while still exercising sub-millisecond and multi-second gaps.
_MAX_MONOTONIC_NS = 10 ** 15


def monotonic_timestamps() -> st.SearchStrategy[tuple[int, int, int, int]]:
    """A Hypothesis strategy generating non-decreasing phase-boundary timestamps.

    Yields a tuple ``(t0, t1, t2, t3)`` of nanosecond integers captured on a
    single monotonic clock satisfying ``t0 <= t1 <= t2 <= t3``, i.e. the four
    C_switch phase boundaries (shutdown / old-exit / new-ready / first-token).

    Generated by drawing four nanosecond values and sorting them, so adjacent
    boundaries may coincide (zero-length phase) or be arbitrarily far apart.
    """
    return st.lists(
        st.integers(min_value=0, max_value=_MAX_MONOTONIC_NS),
        min_size=4,
        max_size=4,
    ).map(lambda xs: tuple(sorted(xs)))


# Peak footprint range (MiB): finite, non-negative, bounded to a plausible
# device-memory window so the feasibility arithmetic stays well-behaved.
_PEAK_MIB = st.floats(
    min_value=0.0, max_value=80_000.0, allow_nan=False, allow_infinity=False
)


@st.composite
def budgets(draw):
    """A Hypothesis strategy for feasibility-filtering inputs (Property 9).

    Yields a tuple ``(peaks, budget)`` where:

    - ``peaks`` is a mapping of :class:`Config` -> measured peak footprint (MiB).
      Keys are drawn from the small Config pools (so distinct Configs are
      generated) and each maps to a finite, non-negative peak.
    - ``budget`` is a finite, non-negative memory budget (MiB) drawn from the
      same range as the peaks, so generated budgets land both below and above
      typical peak values and the feasible/infeasible split is exercised.

    The map may be empty and is built from a list of (Config, peak) pairs, so
    duplicate Configs collapse to a single entry (last write wins) — matching
    how a real per-Config peak table behaves.
    """
    pairs = draw(
        st.lists(
            st.tuples(configs(), _PEAK_MIB),
            max_size=8,
        )
    )
    peaks = {config: peak for config, peak in pairs}
    budget = draw(_PEAK_MIB)
    return peaks, budget


# --------------------------------------------------------------------------- #
# Campaign validation strategy (Property 14)
# --------------------------------------------------------------------------- #

# The set of single-defect variants a generated campaign may carry. ``None``
# marks a fully-valid campaign; every other value names exactly one defect to
# inject, so the consuming property test sees the full "accept iff valid" split.
_VALIDATION_DEFECTS = (
    None,  # fully valid campaign
    "unknown_platform",
    "missing_server_binary",
    "missing_model_file",
    "empty_grid",
    "run_repeats_too_low",
    "unknown_module",
    "decode_batch_out_of_range",
)

# Platform descriptors that are guaranteed NOT to be recognized, used to inject
# the ``unknown_platform`` defect. Kept distinct from RECOGNIZED_PLATFORMS.
_UNKNOWN_PLATFORMS = ("a100", "jetson", "cpu", "tpu-v4", "unknown-platform", "")

# Module names that are guaranteed not to be one of the six known modules.
_UNKNOWN_MODULES = ("Nonexistent_Module", "Switch", "Profiler", "foo")

# Decode-batch values outside the inclusive 1..128 range.
_OUT_OF_RANGE_BATCHES = (0, -1, 129, 256, 1000)


@st.composite
def campaign_defs(draw):
    """A Hypothesis strategy describing valid and invalid campaign definitions.

    Yields an abstract description (a plain dict) of one campaign carrying at
    most one defect (``description["defect"]`` is ``None`` for a fully-valid
    campaign, or names the single injected defect). The description is
    intentionally filesystem-free: the consuming property test materializes real
    temp files (server binary + model files) and builds the concrete
    :class:`~profile_suite.campaign.CampaignConfig` from it, so the strategy has
    no side effects.

    The defects cover every clause of Property 14: unrecognized Platform, a
    missing server binary, a missing model file, an empty Config_Grid, a
    Run_Repeat count < 1, an unknown module name, and an out-of-range
    Decode_Batch_Size value.
    """
    return {
        "defect": draw(st.sampled_from(_VALIDATION_DEFECTS)),
        "platform": draw(st.sampled_from(list(RECOGNIZED_PLATFORMS))),
        "n_quants": draw(st.integers(min_value=1, max_value=3)),
        "ctx_lengths": tuple(
            draw(st.lists(st.sampled_from(_CTX_LENGTHS), min_size=1, max_size=3, unique=True))
        ),
        "slot_counts": tuple(
            draw(st.lists(st.sampled_from(_SLOT_COUNTS), min_size=1, max_size=3, unique=True))
        ),
        "run_repeats": draw(st.integers(min_value=1, max_value=10)),
        "bad_run_repeats": draw(st.integers(max_value=0)),
        "bad_platform": draw(st.sampled_from(_UNKNOWN_PLATFORMS)),
        "bad_module": draw(st.sampled_from(_UNKNOWN_MODULES)),
        "out_of_range_batch": draw(st.sampled_from(_OUT_OF_RANGE_BATCHES)),
    }
